"""empty message

Revision ID: e01b36783b5a
Revises: 16121e85ac8e
Create Date: 2022-08-18 13:48:15.973434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e01b36783b5a'
down_revision = '16121e85ac8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('venue_id', sa.Integer(), nullable=False))
    op.add_column('shows', sa.Column('start_time', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'shows', 'venues', ['venue_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shows', type_='foreignkey')
    op.drop_column('shows', 'start_time')
    op.drop_column('shows', 'venue_id')
    # ### end Alembic commands ###
